# This file was generated by GoReleaser. DO NOT EDIT.
cask "cli-agent-lint" do
  version "0.3.4"

  on_macos do
    on_intel do
      url "https://github.com/Camil-H/cli-agent-lint/releases/download/v#{version}/cli-agent-lint_#{version}_darwin_amd64.tar.gz"
      sha256 "85363a86d3183d1b1c11402432826cb614c2c1d83d7a566dc09ee5373708c358"
    end
    on_arm do
      url "https://github.com/Camil-H/cli-agent-lint/releases/download/v#{version}/cli-agent-lint_#{version}_darwin_arm64.tar.gz"
      sha256 "4421abda6a5b9688e1b34cfbbbf0f0ac1168cc0ddffc60e636669e22d9e8740a"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/Camil-H/cli-agent-lint/releases/download/v#{version}/cli-agent-lint_#{version}_linux_amd64.tar.gz"
      sha256 "d3b3bd996d37404ac71a93ce7c6e5cec6be570445f5f8561390f6ff2c95ed2a2"
    end
    on_arm do
      url "https://github.com/Camil-H/cli-agent-lint/releases/download/v#{version}/cli-agent-lint_#{version}_linux_arm64.tar.gz"
      sha256 "cfeb6ad687ad77ffc7e1c591b32346df14434413ba623cadba9c600a9030602c"
    end
  end

  name "cli-agent-lint"
  desc "Audit CLI tools for AI agent-readiness"
  homepage "https://github.com/Camil-H/cli-agent-lint"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "cli-agent-lint"
  generate_completions_from_executable "bin/cli-agent-lint",
    shell_parameter_format: :cobra,
    shells: [:bash, :zsh, :fish]

  # No zap stanza required

end
