# This file was generated by GoReleaser. DO NOT EDIT.
cask "cli-agent-lint" do
  version "0.3.3"

  on_macos do
    on_intel do
      url "https://github.com/Camil-H/cli-agent-lint/releases/download/v#{version}/cli-agent-lint_#{version}_darwin_amd64.tar.gz"
      sha256 "660f9911eebd6e1646c42e695cd2fa242fec10c6be0fec12b3ff180a6afb6162"
    end
    on_arm do
      url "https://github.com/Camil-H/cli-agent-lint/releases/download/v#{version}/cli-agent-lint_#{version}_darwin_arm64.tar.gz"
      sha256 "fa908b9e6d6937b9021a325c26fc0034de58c18a8618785da79d9b7d4731ec44"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/Camil-H/cli-agent-lint/releases/download/v#{version}/cli-agent-lint_#{version}_linux_amd64.tar.gz"
      sha256 "32b7b7a5e11f06e06d8c1790896285a343add6b251d8c730342f940519f00234"
    end
    on_arm do
      url "https://github.com/Camil-H/cli-agent-lint/releases/download/v#{version}/cli-agent-lint_#{version}_linux_arm64.tar.gz"
      sha256 "2128f1be8a45c997c47bd73017783c88141b44760867289aab3ff0b414443a26"
    end
  end

  name "cli-agent-lint"
  desc "Audit CLI tools for AI agent-readiness"
  homepage "https://github.com/Camil-H/cli-agent-lint"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "cli-agent-lint"
  generate_completions_from_executable "bin/cli-agent-lint", "completion",
    shell_parameter_format: :cobra,
    shells: [:bash, :zsh, :fish]

  # No zap stanza required

end
