# This file was generated by GoReleaser. DO NOT EDIT.
cask "cli-agent-lint" do
  version "0.3.5"

  on_macos do
    on_intel do
      sha256 "b66ccdbddc5d11723dc0f3759f219bb41e163fe0d1ad4d3883fcb3c66231decf"
      url "https://github.com/Camil-H/cli-agent-lint/releases/download/v#{version}/cli-agent-lint_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "6dd4b3b664be7c611160516f092401c8effa60c14bdb3b57ad05d9533437f9af"
      url "https://github.com/Camil-H/cli-agent-lint/releases/download/v#{version}/cli-agent-lint_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "e8546002261662af456460272351f0b08fcfee2af95360e2cc5bec0b33bba4b1"
      url "https://github.com/Camil-H/cli-agent-lint/releases/download/v#{version}/cli-agent-lint_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "dac6e44b8a2d39414231eb767b030be3576187a9cbdb2c5e93369854bf9266a1"
      url "https://github.com/Camil-H/cli-agent-lint/releases/download/v#{version}/cli-agent-lint_#{version}_linux_arm64.tar.gz"
    end
  end

  name "cli-agent-lint"
  desc "Audit CLI tools for AI agent-readiness"
  homepage "https://github.com/Camil-H/cli-agent-lint"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "cli-agent-lint"
  generate_completions_from_executable "bin/cli-agent-lint",
    shell_parameter_format: :cobra,
    shells: [:bash, :zsh, :fish]

  # No zap stanza required

end
